language: node_js
node_js:
- 0.1
- 0.11
before_script:
- sh -e /etc/init.d/xvfb start && npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: RaXc7NvZaUrt+QGOjllD1ljrvpMhvt9XzY0FtrSkg37Y6RXidU9V9JLV1kC28PGdiSP5DIYB5nwVTbVHfoIQH80gctdZE7JQM2vZq8EQREubF9UPtAHVXcoTEOBdK/osXuDXc9yt14CoDaqWg7yBrP/vL28cDYgYFQNN3t8E5rM=
  app: banana-surprise-1671
  on:
    repo: samarpanda/node-http-shell
